name: Linter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: ok-nick/setup-aftman@v0.3.0
      with:
        version: "^1.0.0"
        token: ${{ secrets.GIT_TOKEN }}
    - name: Run Selene Linter
      run: selene .